site_name: 'Fedecan | Fédécan'
site_description: |
  Dedicated to providing safe and inclusive platforms, we enable Canadians to participate in online communities through federated software.

# copyright: Copyright &copy; PLACEHOLDER

nav:
  - Home: index.md
  - Announcements:
    - announcements/index.md
  - Guides:
    - guides/fediverse.md
    - guides/open-source.md
    - guides/lemmy.md
  - Contact Us: contact.md

theme:
  name: material
  custom_dir: overrides
  language: en

  icon:
    logo: fontawesome/brands/canadian-maple-leaf
  favicon: assets/img/canadian-maple-leaf.svg

  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.select


markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - sane_lists
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - glightbox:
      skip_classes:
        - skip-lightbox
  - search
  - blog:
      blog_dir: announcements
      archive: false
      categories: false
      authors: false
      post_excerpt: required
      pagination_per_page: 10
  - group:
      enabled: !ENV CI
      plugins:
        - social:
            cards_layout_options:
              font_family: Noto Sans

extra:
  generator: false